import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { CartSidebar } from "@/components/cart-sidebar";
import { StoreNavigation } from "@/components/store-navigation";
import { Footer } from "@/components/footer";
import { PromoBanner } from "@/components/promo-banner";
import { WelcomeNotice } from "@/components/welcome-notice";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <StoreNavigation />
        <PromoBanner />
        <WelcomeNotice />
        {children}
        <CartSidebar />
        <Footer />
      </body>
    </html>
  );
}
